# The objective of this GitHub Action is to update the README.md file (if needed)
# when doing a git push
name: Update README Algorithm Tracker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Write README.md
        run: |
          python scripts/update_readme.py
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Update README.md
        run: |
          git add README.md
          git commit -am "updating README.md" ||  true
          git push --force origin HEAD:$GITHUB_REF || true